# Generated by Django 5.2.9 on 2026-01-24 10:40

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0002_alter_networth_table_alter_transactions_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_details',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
