# Generated by Django 5.2.9 on 2026-03-12 21:25

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0003_alter_transactions_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networth',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(default='Cash'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(default='Cash'),
        ),
    ]
