# Generated by Django 5.2.9 on 2026-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0004_networth_place_transactions_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networth',
            name='place',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='place',
        ),
    ]
