# Generated by Django 5.2.9 on 2026-05-25 13:05

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0005_remove_networth_place_remove_transactions_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='networth',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(default='General'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(default='General'),
        ),
    ]
