# Generated by Django 5.2.13 on 2026-05-25 13:14

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0006_networth_place_transactions_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networth',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='General', null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='General', null=True),
        ),
    ]
