# Generated by Django 5.2.13 on 2026-05-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0007_alter_networth_place_alter_transactions_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networth',
            name='place',
            field=models.CharField(blank=True, default='General', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='place',
            field=models.CharField(blank=True, default='General', max_length=255, null=True),
        ),
    ]
