# Generated by Django 5.2.13 on 2026-05-25 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_management', '0008_alter_networth_place_alter_transactions_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='networth',
            constraint=models.UniqueConstraint(fields=('user', 'currency', 'place'), name='unique_user_currency_place'),
        ),
    ]
