# These are supported funding model platforms

github: [Kbassem10] # Replace with up to 4 GitHub Sponsors-enabled usernames
#patreon: your-patreon-username # Replace with a single Patreon username
#open_collective: your-open-collective-username # Replace with a single Open Collective username
ko_fi: kbassem10
# tidelift: platform-name/package-name # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: project-name # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: your-liberapay-username # Replace with a single Liberapay username
# issuehunt: your-issuehunt-username # Replace with a single IssueHunt username
# lfx_crowdfunding: project-name # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: your-polar-username # Replace with a single Polar username
# buy_me_a_coffee: your-buy-me-a-coffee-username # Replace with a single Buy Me a Coffee username
# thanks_dev: your-thanks-dev-username # Replace with a single thanks.dev username
# custom: ['link1', 'link2'] # Replace with up to 4 custom sponsorship URLs
