# Generated by Django 5.2.7 on 2025-10-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wishlist',
            table='finance_management_wishlist',
        ),
    ]
