# Generated by Django 5.2.9 on 2026-03-12 21:25

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_management', '0003_alter_wishlist_link_alter_wishlist_wish_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(default='Cash'),
        ),
    ]
