# Generated by Django 5.2.9 on 2026-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_management', '0004_wishlist_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='place',
        ),
    ]
