# Generated by Django 5.2.13 on 2026-05-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_management', '0005_remove_wishlist_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='place',
            field=models.CharField(blank=True, default='General', max_length=255, null=True),
        ),
    ]
