# Generated by Django 5.2.5 on 2025-10-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0002_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
