# Generated by Django 5.2.5 on 2025-10-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0003_reports_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
