# Generated by Django 5.2.7 on 2025-10-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0005_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='target',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='NetWorth',
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.DeleteModel(
            name='ScheduledTransaction',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
