# Generated by Django 5.2.7 on 2025-11-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_management', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=10, unique=True)),
                ('rates', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CurrencyExchangeRate',
        ),
    ]
