"""
Django settings for imhotep_finance project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1ogqe*_xg$2$kfkdp582mmb+k(d^x35u$d+n!vri7uwj!rr_61')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

SITE_DOMAIN = config('SITE_DOMAIN', default='http://localhost:8000')
frontend_url = config('frontend_url', default='http://localhost:3000')

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    'backend',
    SITE_DOMAIN.replace('http://', '').replace('https://', ''),
    ]

if DEBUG:
    # Add this to your settings
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # Security settings - keep these as they are
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition
INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'csp',
    'drf_spectacular',
    'accounts',
    'finance_management',
    'scheduled_trans_management',
    'target_management',
    'transaction_management',
    'user_reports',
    'wishlist_management',
]

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Throttling configuration (no custom exception handler needed)
    'DEFAULT_THROTTLE_CLASSES': [
        'imhotep_finance.throttles.CustomUserRateThrottle',
        'imhotep_finance.throttles.CustomAnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/hour',
        'anon': '100/hour',
        'strict_user': '50/hour',
        'auth': '5/minute',
        'login': '5/minute',
        'register': '3/hour',
        'password_reset': '3/hour',
        'transaction_import': '10/hour',
        'bulk_operations': '20/hour',
        'report_generation': '30/hour',
    },
}

# Simple JWT configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'imhotep_finance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Email configuration for verification emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('MAIL_USER')
EMAIL_HOST_PASSWORD = config('MAIL_PASSWORD')

WSGI_APPLICATION = 'imhotep_finance.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_type = config('database_type', default='sqlite3')

if database_type == 'sqlite3':
    #SQLite database for development and testing
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif database_type == 'mysql':
    #Mysql database for production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DATABASE_NAME', default='imhotep_finance_db'),
            'USER': config('DATABASE_USER', default='imhotep_finance_user'),
            'PASSWORD': config('DATABASE_PASSWORD', default='imhotep_finance_password'),
            'HOST': config('DATABASE_HOST', default='localhost'),
            'PORT': '3306',
            'OPTIONS': {
                'charset': 'utf8mb4',  # Optional: Set the character set
            },
        }
    }

elif database_type == 'postgresql':
    #Postgresql database for production
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DATABASE_NAME', default='imhotep_finance_db'),
            'USER': config('DATABASE_USER', default='imhotep_finance_user'),
            'PASSWORD': config('DATABASE_PASSWORD', default='imhotep_finance_password'),
            'HOST': config('DATABASE_HOST', default='localhost'), 
            'PORT': '5432',
        },
        'backup_source': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'old_data/database_2026-01-24.db',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Simplified password validators - only minimum length requirement
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,  # Reduced minimum length for easier password changes
        }
    },
]

# For no password validation at all, use empty list:
# AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    frontend_url,
    SITE_DOMAIN
]

# CORS settings for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    frontend_url,
    SITE_DOMAIN
]

# Add logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'Chef.views': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Add this configuration for Google OAuth
GOOGLE_OAUTH2_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_OAUTH2_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')

# Update SOCIALACCOUNT_PROVIDERS configuration
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH2_CLIENT_ID,
            'secret': GOOGLE_OAUTH2_CLIENT_SECRET,
        },
        'REDIRECT_URI': f"{SITE_DOMAIN}/api/auth/google/callback/",
        'SCOPE': ['profile', 'email'],
    }
}

# drf-spectacular / OpenAPI 3.0 configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Imhotep Finance API',
    'DESCRIPTION': 'API documentation for Imhotep Finance - a personal finance management app. All endpoints are automatically documented from code.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_READ_ONLY_REQUIRED': True,
    # Security scheme for JWT Bearer tokens and OAuth2
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"',
            },
            'OAuth2': {
                'type': 'oauth2',
                'flows': {
                    'authorizationCode': {
                        'authorizationUrl': f'{SITE_DOMAIN}/o/authorize/',
                        'tokenUrl': f'{SITE_DOMAIN}/o/token/',
                        'scopes': {
                            'read': 'Read access to your financial data',
                            'write': 'Write access to create/delete transactions',
                            'transactions:read': 'Read transaction data',
                            'transactions:write': 'Create and delete transactions',
                        }
                    }
                }
            }
        }
    },
    'SECURITY': [{'Bearer': []}, {'OAuth2': []}],
    # Automatic tagging based on URL patterns
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and authorization endpoints'},
        {'name': 'User Profile', 'description': 'User profile and preferences management'},
        {'name': 'Finance Management', 'description': 'Core finance management endpoints (networth, categories)'},
        {'name': 'Transactions', 'description': 'Transaction management (create, update, delete, list, import, export)'},
        {'name': 'Scheduled Transactions', 'description': 'Scheduled/recurring transaction management'},
        {'name': 'Targets', 'description': 'Financial target management and scoring'},
        {'name': 'Reports', 'description': 'User financial reports (monthly, yearly, history)'},
        {'name': 'Wishlist', 'description': 'Wishlist management'},
        {'name': 'Developer Portal', 'description': 'OAuth2 application management for third-party developers'},
        {'name': 'Public API', 'description': 'Public API endpoints for third-party applications (OAuth2 protected)'},
    ],
    # Enable automatic schema generation
    'SERVE_URLCONF': 'imhotep_finance.urls',
    # Better organization
    'SORT_OPERATIONS': False,
    'SORT_TAGS': True,
    # Include all endpoints automatically
    'DISABLE_ERRORS_AND_WARNINGS': False,
}

FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY')

UNFOLD = {
    "COMMAND_PALETTE": {
        "items": [], 
    },
}