# Generated by Django 5.2.7 on 2025-10-21 10:45

import django.db.models.deletion
import scheduled_trans_management.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(default=scheduled_trans_management.models.current_day)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=4)),
                ('scheduled_trans_status', models.CharField(choices=[('Withdraw', 'withdraw'), ('Deposit', 'deposit')], max_length=8)),
                ('scheduled_trans_details', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('last_time_added', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_transaction_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ScheduledTransaction',
                'verbose_name_plural': 'ScheduledTransactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
