# Generated by Django 5.2.9 on 2026-03-12 21:25

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_trans_management', '0003_alter_scheduledtransaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='place',
            field=encrypted_model_fields.fields.EncryptedCharField(default='Cash'),
        ),
    ]
