# Generated by Django 5.2.9 on 2026-03-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_trans_management', '0004_scheduledtransaction_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledtransaction',
            name='place',
        ),
    ]
