# Generated by Django 5.2.13 on 2026-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduled_trans_management', '0005_remove_scheduledtransaction_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='place',
            field=models.CharField(blank=True, default='General', max_length=255, null=True),
        ),
    ]
