# Generated by Django 5.2.9 on 2026-01-24 10:40

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reports', '0002_alter_reports_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='data',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
