# Generated by Django 5.2.7 on 2025-10-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('target_management', '0002_alter_target_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='target',
            table='finance_management_target',
        ),
    ]
