name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment file
      run: cp backend/imhotep_finance/.env.example backend/imhotep_finance/.env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run tests
      run: |
        docker compose up --build -d db
        # wait for DB to be healthy
        until docker compose exec -T db pg_isready -U imhotep_finance_user; do
          echo "Waiting for Postgres..."; sleep 2;
        done
        # run migrations and tests in one go
        docker compose run --rm backend sh -c "
          python manage.py migrate &&
          python manage.py test finance_management.tests
        "

    - name: Tear down services
      if: always()
      run: docker compose down -v
